### PR TITLE
Bugfix: truncate_with_package_name STRATEGY do not work

### PR DESCRIPTION
**Pull request by Xiongqi-XQ**
#### Description
fix uncate_with_package_name STRATEGY do not work

### CODE REVIEW

**Comment by romkatv** [comment]
FYI: It works correctly in [Powerlevel10k](https://github.com/romkatv/powerlevel10k/blob/master/README.md#for-powerlevel9k-users). It's also faster.

**Comment by Xiongqi-XQ** [comment]
thanks,i'll try it

**Comment by romkatv** [comment]
FYI: I've opened https://github.com/bhilburn/powerlevel9k/issues/1296 (the fix in this PR doesn't work, unfortunately).

**Comment by romkatv** [comment]
@Xiongqi-XQ Could you mention why you've closed this PR?

**Pull request closed without merging**
